### ISSUE TITLE
Download Nordic SDK fails

### ISSUE THREAD

**Issue by djewiss** [dobots/crownstone-sdk#1]
Hi there, the install.sh scripts fails after getting the Nordic SDK, it downloads OK, but returns a "Failed to get Nordic SDK" at the end of the Download.

**Comment by djewiss** [comment]
To work around this, I downloaded manually to the bluenet-workspace/tmp directory and removed lines 59-63

**Comment by mrquincle** [comment]
@djewiss Interesting failure. I don't know exactly where it comes from.
1. I just checked the URL, it should be correct.
2. It is in particular specified that it is a bash script. So, no errors stemming from that.
3. It might be a different wget version that does return an error code if it succeeds to download the right file.

We use `if [[ $? -ne 0 ]]; then` to check if a command is successful. Two things you might help us with are (a) figuring out your wget version, (b) checking `echo $?` after manually downloading it.

Good you figured it out anyway of course. :+1:

**Comment by djewiss** [comment]
Hi Anne

wget is version 1.15

wget https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v11.x.x/nRF5_SDK_11.0.0_89a8197.zip
echo $?

returns 1

**Comment by mrquincle** [comment]
@djewiss Nice, that's very interesting. :-)

I suppose that's also the case for:

```
wget https://google.com && echo $?
```

Normally wget has nice error codes. If you abort for example you get 130, if you have a domain name that cannot be resolved it will be 4 (which will also be the case if you don't have a good internet connection). The only way I could get a "generic error" like you have is by running `wget` without arguments.

However, if you've run the arguments like you described directly from the command-line. I'm running out of options. The script itself is defined as `bash`, but to make sure, which shell do you use? 

```
ps -p $$
```

If you do not mind can you drop the entire output of wget on the command-line here? 

```
https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v11.x.x/nRF5_SDK_11.0.0_89a8197.zip && echo $?
```

**Comment by djewiss** [comment]
Hi there

Sorry for the delay, I got distracted! 
ps -p $$ returns-
  PID TTY          TIME CMD
30550 pts/0    00:00:00 bash

https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v11.x.x/nRF5_SDK_11.0.0_89a8197.zip && echo $?
returns
bash: https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v11.x.x/nRF5_SDK_11.0.0_89a8197.zip: No such file or directory

Thx Darryl

**Comment by mrquincle** [comment]
Oops, needs to be

`wget https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v11.x.x/nRF5_SDK_11.0.0_89a8197.zip && echo $?
`

**Comment by mrquincle** [comment]
Just like 

`wget https://google.com && echo $?`

**Comment by mrquincle** [comment]
Changed to github release system at https://github.com/crownstone/crownstone-sdk/blob/master/scripts/install.sh#L9 to reduce dependencies on third-party URLs.
