### ISSUE TITLE
Login fail

### ISSUE THREAD

**Issue by giacomo270197** [dobots/crownstone-sdk#2]
Hello,
I am trying to login via the API using the credentials of an account I created via the app.
However, this seems not to be possible.

The request is successful is it is made to the following endpoint:
`https://cloud.crownstone.rocks/login` (the one to log into the explorer),

But not if it is made to the login endpoint:
`https://cloud.crownstone.rocks/api/user/login`

I am passing the same credentials.
Any idea?

Thank you in advance

**Comment by AlexDM0** [comment]
Hi Giacomo,

You have to pass the following to the login endpoint:

{"email":"your_email@host.com", "password":"sha1-hash-of-password"}

So if your plaintext password is "abcde", you should pass
"03de6c570bfe24bfc328ccd7ca46b76eadaf4334" as password. (quick hash from
http://www.sha1-online.com/)

Regards,

Alex

**Comment by giacomo270197** [comment]
Alright thank you
